### PR TITLE
Associate primary network interface SG with the trunk-eni when SG is not specified in ENIConfig

### LINKED ISSUE #189: If a custom network is used and no security group is specified on ENIConfig, the VPC default security group is attached to the trunk ENI
**Describe the Bug**:

I verified this behavior using the following version.

- EKS cluster version
  1.25
- Platform version
  eks.1
- Amazon VPC CNI Plugin
  v1.12.2

When trunk ENI is created, the attaching security groups are chosen based on whether the node is using custom network.

https://github.com/aws/amazon-vpc-resource-controller-k8s/blob/f45d01905177fa6146e2fdfdf0792c0e78dc3fb3/pkg/aws/ec2/instance.go#L238-L258

And if the node is using a custom network, the vpc resource controller uses ENIConfig's spec.securityGroups for trunk ENI. However, if this is not specified on ENIConfig, the default security group for VPC will be used as specification for the CreateNetworkInterface API. This differs in behavior from the following specifications.

https://github.com/awsdocs/amazon-eks-user-guide/blob/086ca837b806e2fe73702f2cc1c827c677207ebb/doc_source/cni-custom-network.md?plain=1#L293-L296

If no security group is specified on ENIConfig, I believe that the primary ENI's security group should also be used for trunk ENI.

**Observed Behavior**:

If a custom network is used and no security group is specified on ENIConfig, the VPC default security group is attached to the trunk ENI

**Expected Behavior**:

The primary ENI's security groups are used for trunk ENI

**How to reproduce it (as minimally and precisely as possible)**:

1. Execute the following command.

```
kubectl set env daemonset aws-node -n kube-system ENABLE_POD_ENI=true

cat <<EOF | kubectl apply -f -
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1 
kind: ENIConfig
metadata:
  name: us-west-2a
spec:
  subnet: subnet-XXXXXXXX
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1 
kind: ENIConfig
metadata:
  name: us-west-2b
spec:
  subnet: subnet-YYYYYYYY
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1 
kind: ENIConfig
metadata:
  name: us-west-2c
spec:
  subnet: subnet-ZZZZZZZZ
EOF

kubectl set env daemonset aws-node -n kube-system AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true
kubectl set env daemonset aws-node -n kube-system ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone
```
2. Create a new node.

3. Check the trunk ENI's security group.

**Additional Context**:

none.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25.6
- CNI Version: v1.12.2
- OS (Linux/Windows): Linux

### PR DESCRIPTION
**Pull request by sushrk**
*Issue #, if available:*
Fixes #189 

*Description of changes:*
Currently, when security group is not specified in ENIConfig, the trunk ENI is associated with the default security group of the VPC. The expected behavior when using vpc-cni >= v1.8.0 is to use the primary network interface security groups with secondary network interfaces. 

Changes in this PR is to associate the trunk ENI with the primary network interface security groups when ENIConfig is missing security groups. 

*Testing:*

1. Created two eniconfigs as follows-
```
[10/05/23 1:34:11] ➜  ~ kubectl get eniconfigs.crd.k8s.amazonaws.com -o yaml
apiVersion: v1
items:
- apiVersion: crd.k8s.amazonaws.com/v1alpha1
  kind: ENIConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"crd.k8s.amazonaws.com/v1alpha1","kind":"ENIConfig","metadata":{"annotations":{},"name":"us-west-2a"},"spec":{"securityGroups":["sg-1111111111"],"subnet":"subnet-1111111111"}}
    creationTimestamp: "2023-04-24T23:07:30Z"
    generation: 4
    name: us-west-2a
    resourceVersion: "11479510"
    uid: a261d5a8-8aea-4df4-a1b5-05e2525ea395
  spec:
    securityGroups:
    - sg-1111111111
    subnet: subnet-1111111111
- apiVersion: crd.k8s.amazonaws.com/v1alpha1
  kind: ENIConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"crd.k8s.amazonaws.com/v1alpha1","kind":"ENIConfig","metadata":{"annotations":{},"name":"us-west-2b"},"spec":{"subnet":"subnet-2222222222"}}
    creationTimestamp: "2023-04-27T16:05:58Z"
    generation: 3
    name: us-west-2b
    resourceVersion: "6314138"
    uid: f80f995b-a1fc-4d56-a93d-b4dab5b60546
  spec:
    subnet: subnet-2222222222
kind: List
metadata:
  resourceVersion: ""
```
In v1.1.5, the trunk ENI of the instance in `us-west-2b` is associated with the default security group of the VPC. Verified that with the changes in this PR the trunk ENI is associated with the primary network interface security groups. 
Also verified with correct ENIConfigs that the trunk ENI is associated with the SG specified in the ENIConfig

2. Ran all SGP tests in non-custom networking cluster to verify no regression issues- (skipping LOCAL tests)
```
Running Suite: Per Pod Security Group Suite - /home/ravsushm/go/src/github.com/aws/amazon-vpc-resource-controller-k8s/test/integration/perpodsg
===============================================================================================================================================
Random Seed: 1683852685

Will run 18 of 22 specs
-- redacted--

[AfterSuite] 
/home/ravsushm/go/src/github.com/aws/amazon-vpc-resource-controller-k8s/test/integration/perpodsg/perpodsg_suite_test.go:58
  STEP: waiting for all the ENIs to be deleted after being cooled down @ 05/12/23 01:12:50.433
[AfterSuite] PASSED [90.552 seconds]
------------------------------

Ran 18 of 22 Specs in 1372.557 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 4 Skipped
PASS

```

*Release Notes:* 
This PR introduces a breaking change. Starting in v1.1.6+, when security groups are not specified in ENIConfig with custom networking enabled, the trunk ENI will be associated with the security group of the primary network interface rather than the default security group of the VPC. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: pkg/aws/ec2/instance.go [hunk 1]
```diff
@@ -192,8 +192,9 @@ func (i *ec2Instance) PrimaryNetworkInterfaceID() string {
 	return i.primaryENIID
 }
 
-// InstanceSecurityGroup returns the instance security group of the primary network interface
-func (i *ec2Instance) InstanceSecurityGroup() []string {
+// CurrentInstanceSecurityGroup returns the current instance security
```
Comment (haouc) [inline pkg/aws/ec2/instance.go:195]: nit: missing `group` at the end

File: pkg/aws/ec2/instance.go [hunk 2]
```diff
@@ -192,8 +192,9 @@ func (i *ec2Instance) PrimaryNetworkInterfaceID() string {
...
+// (primary network interface SG or SG specified in the ENIConfig
```
Comment (haouc) [inline pkg/aws/ec2/instance.go:196]: nit: missing `)` at the end.

File: pkg/aws/ec2/instance.go [hunk 3]
```diff
@@ -253,7 +254,12 @@ func (i *ec2Instance) updateCurrentSubnetAndCidrBlock(ec2APIHelper api.EC2APIHel
 	// Custom networking is being used on node, point the current subnet ID, CIDR block and
 	// instance security group to the one's present in the Custom networking spec
 	if i.newCustomNetworkingSubnetID != "" {
-		i.currentInstanceSecurityGroup = i.newCustomNetworkingSecurityGroup
+		if i.newCustomNetworkingSecurityGroup != nil && len(i.newCustomNetworkingSecurityGroup) > 0 {
```
Comment (haouc) [inline pkg/aws/ec2/instance.go:257]: nit: probably use plural since this is a slice of SG

File: pkg/node/manager/manager_test.go [hunk 4]
```diff
@@ -246,6 +255,33 @@ func Test_AddNode_CustomNetworking(t *testing.T) {
 	assert.True(t, AreNodesEqual(mock.Manager.dataStore[nodeName], managedNode))
 }
 
+// Test adding node when custom networking is enabled but incorrect ENIConfig is defined; it should succeed
+func Test_AddNode_CustomNetworking_Incorrect_ENIConfig(t *testing.T) {
```
Comment (haouc) [inline pkg/node/manager/manager_test.go:259]: Seems this can be combined into a table driven tests with the `Test_AddNode_CustomNetworking` and `Test_AddNode_CustomNetworking_NoENIConfig`, or event others. But we can refactor them later. No need to update in this PR. Maybe you can add a `TODO` comment for tracking.

File: scripts/gen_mocks.sh [hunk 5]
```diff
@@ -24,4 +24,4 @@ mockgen -destination=../mocks/amazon-vcp-resource-controller-k8s/pkg/pool/mock_p
 # package resource maocks
 mockgen -destination=../mocks/amazon-vcp-resource-controller-k8s/pkg/resource/mock_resources.go github.com/aws/amazon-vpc-resource-controller-k8s/pkg/resource ResourceManager
 # package condition maocks
-mockgen -destination=../mocks/amazon-vcp-resource-controller-k8s/pkg/condition/mock_condtion.go github.com/aws/amazon-vpc-resource-controller-k8s/pkg/condition Conditions
+mockgen -destination=../mocks/amazon-vcp-resource-controller-k8s/pkg/condition/mock_condition.go github.com/aws/amazon-vpc-resource-controller-k8s/pkg/condition Conditions
```
Comment (haouc) [inline scripts/gen_mocks.sh:27]: Is this called from anywhere in automation or tests? I am not sure if you want to make this chanege without including the impacted files in this PR.

**Review by haouc — COMMENTED** [review]
Overall looks good to me. Just some nit comments and one question. Thanks

File: scripts/gen_mocks.sh (hunk 5 above)
Comment (sushrk) [reply scripts/gen_mocks.sh:27]: `mock_condtion.go` was renamed to `mock_condition.go` in #166,  and `mock_condtion` has no references in the repo- I think this is safe to commit.

**Review by haouc — APPROVED** [review]
lgtm
